// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: seckill.proto

/*
Package zhiliao_seckill_srv is a generated protocol buffer package.

It is generated from these files:
	seckill.proto

It has these top-level messages:
	SecKillRequest
	SecKillResponse
*/
package zhiliao_seckill_srv

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for SecKill service

type SecKillService interface {
	FrontSecKill(ctx context.Context, in *SecKillRequest, opts ...client.CallOption) (*SecKillResponse, error)
}

type secKillService struct {
	c    client.Client
	name string
}

func NewSecKillService(name string, c client.Client) SecKillService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "zhiliao_seckill_srv"
	}
	return &secKillService{
		c:    c,
		name: name,
	}
}

func (c *secKillService) FrontSecKill(ctx context.Context, in *SecKillRequest, opts ...client.CallOption) (*SecKillResponse, error) {
	req := c.c.NewRequest(c.name, "SecKill.FrontSecKill", in)
	out := new(SecKillResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SecKill service

type SecKillHandler interface {
	FrontSecKill(context.Context, *SecKillRequest, *SecKillResponse) error
}

func RegisterSecKillHandler(s server.Server, hdlr SecKillHandler, opts ...server.HandlerOption) error {
	type secKill interface {
		FrontSecKill(ctx context.Context, in *SecKillRequest, out *SecKillResponse) error
	}
	type SecKill struct {
		secKill
	}
	h := &secKillHandler{hdlr}
	return s.Handle(s.NewHandler(&SecKill{h}, opts...))
}

type secKillHandler struct {
	SecKillHandler
}

func (h *secKillHandler) FrontSecKill(ctx context.Context, in *SecKillRequest, out *SecKillResponse) error {
	return h.SecKillHandler.FrontSecKill(ctx, in, out)
}
