// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: admin_user.proto

/*
Package zhiliao_user_srv is a generated protocol buffer package.

It is generated from these files:
	admin_user.proto

It has these top-level messages:
	FrontUsersRequest
	FrontUsersResponse
	FrontUser
	AdminUserRequest
	AdminUserResponse
*/
package zhiliao_user_srv

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for AdminUser service

type AdminUserService interface {
	AdminUserLogin(ctx context.Context, in *AdminUserRequest, opts ...client.CallOption) (*AdminUserResponse, error)
	FrontUserList(ctx context.Context, in *FrontUsersRequest, opts ...client.CallOption) (*FrontUsersResponse, error)
}

type adminUserService struct {
	c    client.Client
	name string
}

func NewAdminUserService(name string, c client.Client) AdminUserService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "zhiliao_user_srv"
	}
	return &adminUserService{
		c:    c,
		name: name,
	}
}

func (c *adminUserService) AdminUserLogin(ctx context.Context, in *AdminUserRequest, opts ...client.CallOption) (*AdminUserResponse, error) {
	req := c.c.NewRequest(c.name, "AdminUser.AdminUserLogin", in)
	out := new(AdminUserResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminUserService) FrontUserList(ctx context.Context, in *FrontUsersRequest, opts ...client.CallOption) (*FrontUsersResponse, error) {
	req := c.c.NewRequest(c.name, "AdminUser.FrontUserList", in)
	out := new(FrontUsersResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AdminUser service

type AdminUserHandler interface {
	AdminUserLogin(context.Context, *AdminUserRequest, *AdminUserResponse) error
	FrontUserList(context.Context, *FrontUsersRequest, *FrontUsersResponse) error
}

func RegisterAdminUserHandler(s server.Server, hdlr AdminUserHandler, opts ...server.HandlerOption) error {
	type adminUser interface {
		AdminUserLogin(ctx context.Context, in *AdminUserRequest, out *AdminUserResponse) error
		FrontUserList(ctx context.Context, in *FrontUsersRequest, out *FrontUsersResponse) error
	}
	type AdminUser struct {
		adminUser
	}
	h := &adminUserHandler{hdlr}
	return s.Handle(s.NewHandler(&AdminUser{h}, opts...))
}

type adminUserHandler struct {
	AdminUserHandler
}

func (h *adminUserHandler) AdminUserLogin(ctx context.Context, in *AdminUserRequest, out *AdminUserResponse) error {
	return h.AdminUserHandler.AdminUserLogin(ctx, in, out)
}

func (h *adminUserHandler) FrontUserList(ctx context.Context, in *FrontUsersRequest, out *FrontUsersResponse) error {
	return h.AdminUserHandler.FrontUserList(ctx, in, out)
}
